services:  
    
  # iris
  iris:
    init: true
    container_name: iris
    build:
      context: .
      dockerfile: iris/Dockerfile
    ports:
      - 52774:52773
      - 51774:1972
    volumes:
    - ./shared:/shared
    environment:
      ISC_DATA_DIRECTORY: /shared/durable
      IRIS_NAMESPACE: QUINIELA
      IRIS_USERNAME: testuser
      IRIS_PASSWORD: testpassword
    command: --check-caps false --ISCAgent false --key /shared/iris.key

  webgateway:
    init: true
    container_name: webgateway
    build:
      context: .
      dockerfile: webgateway/Dockerfile
    hostname: webgateway
    ports:
    - "8080:80"
    - "8443:443"
    environment:
    - ISC_DATA_DIRECTORY=/webgateway-shared/durable
    - ISC_CSP_CONF_FILE=/webgateway-shared/CSP.conf
    - ISC_CSP_INI_FILE=/webgateway-shared/CSP.ini
    volumes:
    - ./webgateway/shared:/webgateway-shared
    depends_on:
    - iris  

# angular
  angular:
    init: true
    container_name: quiniela-ui
    build:
      context: .
      dockerfile: quiniela-ui/Dockerfile
    ports:
      - 81:80
      - 443:443
    depends_on:
      - iris
